wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.31
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.10
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      4: 3.7.10
      5: 0.10.31
      8:
      - 5
batch_size:
  desc: null
  value: 200
epochs:
  desc: null
  value: 1000
learning_rate:
  desc: null
  value: 0.001
optimizer:
  desc: null
  value: Adam
